# -*- coding: utf-8 -*-
"""Huggingface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sLM9NBHrUwsd3cygZ3UzauaDTFfB44L
"""

# Import the pipeline
from transformers import pipeline

# Load GPT-2 text generation pipeline
gen = pipeline("text-generation", model="gpt2")

# Generate text with temperature control
output = gen("The wizard cast a",
             max_length=10,
             do_sample=True,
             temperature=1.2)

# Print output
print(output[0]['generated_text'])